resource_types:
- name: bosh-release
  type: registry-image
  source: {repository: dpb587/bosh-release-resource}

- name: bosh-deployment
  type: registry-image
  source: {repository: cloudfoundry/bosh-deployment-resource}

resources:
- name: concourse-release-latest
  type: bosh-io-release
  source:
    repository: concourse/concourse-bosh-release

- name: concourse-release-branch
  type: bosh-release
  source:
    uri: https://github.com/concourse/concourse-bosh-release
    branch: ((branch_name))
    dev_releases: true

- name: cbd-master
  type: git
  source:
    uri: https://github.com/concourse/concourse-bosh-deployment
    branch: master

- name: cbd-develop
  type: git
  source:
    uri: https://github.com/concourse/concourse-bosh-deployment
    branch: develop

- name: postgres-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/postgres-release

- name: bpm-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/bpm-release

- name: gcp-xenial-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-xenial-go_agent

- name: deployment
  type: bosh-deployment
  source:
    target: ((bosh_target))
    client: ((bosh_client.id))
    client_secret: ((bosh_client.secret))
    deployment: concourse-((environment))

jobs:
- name: deploy-latest
  serial: true
  interruptible: true
  plan:
  - in_parallel:
    - get: concourse-release-latest
    - get: postgres-release
    - get: bpm-release
    - get: gcp-xenial-stemcell
    - get: cbd-master
  - put: deployment
    params:
      manifest: cbd-master/cluster/concourse.yml
      stemcells:
      - gcp-xenial-stemcell/*.tgz
      releases:
      - concourse-release-latest/*.tgz
      - postgres-release/*.tgz
      - bpm-release/*.tgz
      ops_files:
      - cbd-master/cluster/operations/web-network-extension.yml
      - cbd-master/cluster/operations/add-local-users.yml
      - cbd-master/cluster/operations/scale.yml
      - cbd-master/cluster/operations/privileged-http.yml
      - cbd-master/cluster/operations/debug-concourse.yml

      - cbd-master/cluster/operations/syslog_forwarder.yml
      - cbd-master/cluster/operations/db-stats.yml
      - cbd-master/cluster/operations/datadog.yml

      - cbd-master/cluster/operations/enable-global-resources.yml
      vars_files:
      - cbd-master/versions.yml
      vars: &vars
        deployment_name: concourse-((environment))
        external_url: "http://((environment)).concourse-ci.org"
        network_name: private
        web_network_name: web
        web_network_vm_extension: ((environment))-web-target-pool
        web_vm_type: web
        db_vm_type: database
        worker_vm_type: worker
        db_persistent_disk_type: super-extra-large
        add_local_users: [((environment)):((admin_password))]
        main_team_local_users: [((environment))]
        web_instances: 2
        worker_instances: 10
        syslog_address: logs7.papertrailapp.com
        syslog_port: '48310'
        syslog_permitted_peer: "*.papertrailapp.com"
        datadog_api_key: ((datadog_api_key))
        datadog_tags: ["bosh-deployment:concourse-((environment))"]

- name: deploy-branch
  serial: true
  interruptible: true
  plan:
  - in_parallel:
    - get: concourse-release-branch
    - get: postgres-release
    - get: bpm-release
    - get: gcp-xenial-stemcell
    - get: cbd-develop
  - put: deployment
    params:
      manifest: cbd-develop/cluster/concourse.yml
      stemcells:
      - gcp-xenial-stemcell/*.tgz
      releases:
      - concourse-release-branch/*.tgz
      - postgres-release/*.tgz
      - bpm-release/*.tgz
      ops_files:
      - cbd-develop/cluster/operations/web-network-extension.yml
      - cbd-develop/cluster/operations/add-local-users.yml
      - cbd-develop/cluster/operations/scale.yml
      - cbd-develop/cluster/operations/privileged-http.yml
      - cbd-develop/cluster/operations/debug-concourse.yml

      - cbd-develop/cluster/operations/syslog_forwarder.yml
      - cbd-develop/cluster/operations/db-stats.yml
      - cbd-develop/cluster/operations/datadog.yml

      - cbd-develop/cluster/operations/dev-versions.yml
      vars_files:
      - cbd-develop/versions.yml
      vars: *vars
